//! XOR-based Forward Error Correction for OAAT audio packets.
//!
//! Every `group_size` data packets, a parity packet is generated by XORing
//! all data payloads in the group (zero-extended to the longest payload).
//! If any single packet in the group is lost, it can be reconstructed from
//! the parity + the remaining packets. The parity header's `fec_len_xor`
//! carries the XOR of all data payload lengths, so the exact length of a
//! recovered packet is restored (no zero-padding injected into the stream).
//!
//! Wire encoding (see `AudioPacketHeader`): data packets carry
//! `fec_group_size` and `fec_index`; the parity packet carries the FEC flag,
//! `fec_group_size` and `fec_len_xor`, and consumes the sequence number
//! following the group's last data packet.
//!
//! This adds 1/group_size bandwidth overhead (6-50%) but makes Wi-Fi
//! streaming resilient to occasional packet loss without retransmission
//! latency. The receiver buffers one group before emitting, adding
//! `group_size × packet_duration` of latency (≈90 ms for 8 × 480-frame
//! packets at 44.1 kHz) — well within the multi-room play delay.

use crate::wire::{AudioPacketHeader, PacketFlags};

/// Encoder: accumulates packets, emits parity when the group is full.
pub struct FecEncoder {
    group_size: u8,
    parity: Vec<u8>,
    len_xor: u16,
    count: u8,
}

/// Parity data returned when an encoder group completes.
pub struct FecParity {
    pub payload: Vec<u8>,
    pub len_xor: u16,
}

impl FecEncoder {
    pub fn new(group_size: u8) -> Self {
        assert!((2..=16).contains(&group_size));
        Self {
            group_size,
            parity: Vec::new(),
            len_xor: 0,
            count: 0,
        }
    }

    /// Index the NEXT data packet will occupy within its group.
    pub fn next_index(&self) -> u8 {
        self.count
    }

    /// Feed a data packet payload. Returns the parity when the group completes.
    pub fn feed(&mut self, payload: &[u8]) -> Option<FecParity> {
        if self.count == 0 {
            self.parity.clear();
            self.parity.resize(payload.len(), 0);
            self.len_xor = 0;
        }

        if payload.len() > self.parity.len() {
            self.parity.resize(payload.len(), 0);
        }
        for (i, &b) in payload.iter().enumerate() {
            self.parity[i] ^= b;
        }
        self.len_xor ^= payload.len() as u16;

        self.count += 1;

        if self.count >= self.group_size {
            self.count = 0;
            Some(FecParity {
                payload: std::mem::take(&mut self.parity),
                len_xor: self.len_xor,
            })
        } else {
            None
        }
    }

    pub fn group_size(&self) -> u8 {
        self.group_size
    }
}

/// A packet as handled by the receiver: header + payload.
pub type FecPacket = (AudioPacketHeader, Vec<u8>);

/// Receiver: reorders packets within a FEC group, recovers a single loss
/// from the parity, and emits packets in order.
///
/// Packets without FEC (`fec_group_size == 0`) pass through immediately.
/// FEC groups are buffered until complete (or recovered), then emitted in
/// index order. An incomplete group is flushed when the next group starts
/// or on [`FecReceiver::flush`].
pub struct FecReceiver {
    /// Base sequence (index 0) of the group being assembled. None = idle.
    base_seq: Option<u16>,
    /// Base sequence of the most recently flushed group: a straggler from it
    /// is emitted immediately instead of disturbing the current group.
    prev_base_seq: Option<u16>,
    slots: Vec<Option<FecPacket>>,
    parity: Option<(u16, Vec<u8>)>, // (len_xor, payload)
    group_size: u8,
    recovered: u64,
    lost: u64,
}

impl FecReceiver {
    pub fn new() -> Self {
        Self {
            base_seq: None,
            prev_base_seq: None,
            slots: Vec::new(),
            parity: None,
            group_size: 0,
            recovered: 0,
            lost: 0,
        }
    }

    /// Packets recovered from parity so far.
    pub fn recovered(&self) -> u64 {
        self.recovered
    }

    /// Packets lost beyond recovery so far.
    pub fn lost(&self) -> u64 {
        self.lost
    }

    /// Feed a received packet; returns the packets to deliver, in order.
    pub fn feed(&mut self, header: AudioPacketHeader, payload: Vec<u8>) -> Vec<FecPacket> {
        // No FEC on this packet: emit directly (flushing any group in
        // progress first, so ordering is preserved when FEC gets disabled
        // mid-stream).
        if header.fec_group_size == 0 && !header.flags.contains(PacketFlags::FEC) {
            let mut out = self.flush();
            out.push((header, payload));
            return out;
        }

        if header.flags.contains(PacketFlags::FEC) {
            // Parity packet: sequence follows the group's last data packet.
            let base = header
                .sequence
                .wrapping_sub(header.fec_group_size as u16);
            if self.base_seq == Some(base) {
                self.parity = Some((header.fec_len_xor, payload));
                return self.try_complete();
            }
            // Parity for an already-flushed (or never-seen) group: useless.
            return Vec::new();
        }

        let base = header.sequence.wrapping_sub(header.fec_index as u16);

        // Straggler from the previously flushed group: deliver immediately,
        // late but without disturbing the current group.
        if self.prev_base_seq == Some(base) && self.base_seq != Some(base) {
            return vec![(header, payload)];
        }

        // Group switch: flush whatever the previous group had.
        let mut out = Vec::new();
        if self.base_seq != Some(base) {
            out = self.flush();
            self.base_seq = Some(base);
            self.group_size = header.fec_group_size;
            self.slots = (0..header.fec_group_size).map(|_| None).collect();
            self.parity = None;
        }

        let idx = header.fec_index as usize;
        if idx < self.slots.len() {
            self.slots[idx] = Some((header, payload));
        }
        out.extend(self.try_complete());
        out
    }

    /// Emit the group if complete, or recover the single missing packet if
    /// the parity is available.
    fn try_complete(&mut self) -> Vec<FecPacket> {
        let missing = self.slots.iter().filter(|s| s.is_none()).count();

        if missing == 0 && !self.slots.is_empty() {
            return self.take_group();
        }

        if missing == 1
            && let Some((len_xor, parity_payload)) = self.parity.take()
        {
            let idx = self
                .slots
                .iter()
                .position(|s| s.is_none())
                .expect("one slot is missing");

            let mut recovered = parity_payload;
            let mut recovered_len = len_xor;
            for slot in self.slots.iter().flatten() {
                for (j, &b) in slot.1.iter().enumerate() {
                    if j < recovered.len() {
                        recovered[j] ^= b;
                    }
                }
                recovered_len ^= slot.1.len() as u16;
            }
            recovered.truncate(recovered_len as usize);

            let header = self.synthesize_header(idx, recovered.len() as u16);
            self.slots[idx] = Some((header, recovered));
            self.recovered += 1;
            return self.take_group();
        }

        Vec::new()
    }

    /// Header for a recovered packet: sequence and FEC fields are exact;
    /// PTS and sample offset are linearly extrapolated from the two nearest
    /// received packets (exact when packets have uniform duration).
    fn synthesize_header(&self, idx: usize, payload_len: u16) -> AudioPacketHeader {
        let known: Vec<(usize, &AudioPacketHeader)> = self
            .slots
            .iter()
            .enumerate()
            .filter_map(|(i, s)| s.as_ref().map(|(h, _)| (i, h)))
            .collect();

        // Group size ≥ 2 and only one packet missing → at least one known.
        let (i0, h0) = known[0];
        let (pts, offset) = if known.len() >= 2 {
            let (i1, h1) = known[1];
            let di = (i1 as i64 - i0 as i64).max(1);
            let pts_step = (h1.pts_ns as i64 - h0.pts_ns as i64) / di;
            let off_step = (h1.sample_offset as i64 - h0.sample_offset as i64) / di;
            let d = idx as i64 - i0 as i64;
            (
                (h0.pts_ns as i64 + pts_step * d).max(0) as u64,
                (h0.sample_offset as i64 + off_step * d).max(0) as u64,
            )
        } else {
            (h0.pts_ns, h0.sample_offset)
        };

        AudioPacketHeader {
            version: h0.version,
            flags: PacketFlags::empty(),
            format: h0.format,
            sequence: self
                .base_seq
                .unwrap_or(0)
                .wrapping_add(idx as u16),
            stream_id: h0.stream_id,
            pts_ns: pts,
            sample_offset: offset,
            payload_len,
            fec_group_size: self.group_size,
            fec_index: idx as u8,
            fec_len_xor: 0,
        }
    }

    fn take_group(&mut self) -> Vec<FecPacket> {
        self.prev_base_seq = self.base_seq.take();
        self.parity = None;
        self.slots.drain(..).flatten().collect()
    }

    /// Emit whatever the current group holds, in order (missing packets are
    /// counted as lost). Call on stream end or before teardown.
    pub fn flush(&mut self) -> Vec<FecPacket> {
        if self.base_seq.is_none() {
            return Vec::new();
        }
        let missing = self.slots.iter().filter(|s| s.is_none()).count() as u64;
        self.lost += missing;
        self.take_group()
    }
}

impl Default for FecReceiver {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::format::AudioFormat;

    fn header(seq: u16, group: u8, index: u8, payload_len: u16) -> AudioPacketHeader {
        AudioPacketHeader {
            version: 1,
            flags: PacketFlags::empty(),
            format: AudioFormat::PcmS16le,
            sequence: seq,
            stream_id: 1,
            pts_ns: 1_000_000_000 + seq as u64 * 10_000_000,
            sample_offset: seq as u64 * 480,
            payload_len,
            fec_group_size: group,
            fec_index: index,
            fec_len_xor: 0,
        }
    }

    fn parity_header(seq: u16, group: u8, len_xor: u16, payload_len: u16) -> AudioPacketHeader {
        AudioPacketHeader {
            flags: PacketFlags::FEC,
            fec_index: 0,
            fec_len_xor: len_xor,
            ..header(seq, group, 0, payload_len)
        }
    }

    fn encode_group(payloads: &[Vec<u8>]) -> FecParity {
        let mut enc = FecEncoder::new(payloads.len() as u8);
        let mut parity = None;
        for p in payloads {
            parity = enc.feed(p);
        }
        parity.expect("group complete")
    }

    #[test]
    fn passthrough_without_fec() {
        let mut rx = FecReceiver::new();
        let out = rx.feed(header(7, 0, 0, 4), vec![1, 2, 3, 4]);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0.sequence, 7);
    }

    #[test]
    fn complete_group_emitted_in_order() {
        let mut rx = FecReceiver::new();
        let payloads: Vec<Vec<u8>> = (0..4u8).map(|i| vec![i; 100]).collect();

        // Deliver out of order: 1, 0, 3, 2
        assert!(rx.feed(header(11, 4, 1, 100), payloads[1].clone()).is_empty());
        assert!(rx.feed(header(10, 4, 0, 100), payloads[0].clone()).is_empty());
        assert!(rx.feed(header(13, 4, 3, 100), payloads[3].clone()).is_empty());
        let out = rx.feed(header(12, 4, 2, 100), payloads[2].clone());

        assert_eq!(out.len(), 4);
        for (i, (h, p)) in out.iter().enumerate() {
            assert_eq!(h.sequence, 10 + i as u16);
            assert_eq!(*p, payloads[i]);
        }
    }

    #[test]
    fn single_loss_recovered_with_exact_length() {
        let mut rx = FecReceiver::new();
        // Different lengths: the recovered packet must get ITS length back,
        // not the parity length.
        let payloads = vec![vec![0xAA; 100], vec![0xBB; 120], vec![0xCC; 90]];
        let parity = encode_group(&payloads);

        assert!(rx.feed(header(20, 3, 0, 100), payloads[0].clone()).is_empty());
        // packet index 1 (seq 21, 120 bytes) lost
        assert!(rx.feed(header(22, 3, 2, 90), payloads[2].clone()).is_empty());
        let out = rx.feed(
            parity_header(23, 3, parity.len_xor, parity.payload.len() as u16),
            parity.payload,
        );

        assert_eq!(out.len(), 3);
        assert_eq!(out[1].0.sequence, 21);
        assert_eq!(out[1].1, payloads[1]);
        assert_eq!(out[1].1.len(), 120);
        // PTS/offset extrapolated exactly for uniform packets
        assert_eq!(out[1].0.pts_ns, header(21, 3, 1, 120).pts_ns);
        assert_eq!(out[1].0.sample_offset, header(21, 3, 1, 120).sample_offset);
        assert_eq!(rx.recovered(), 1);
        assert_eq!(rx.lost(), 0);
    }

    #[test]
    fn two_losses_flushed_as_lost() {
        let mut rx = FecReceiver::new();
        let payloads = vec![vec![1u8; 50], vec![2u8; 50], vec![3u8; 50], vec![4u8; 50]];
        let parity = encode_group(&payloads);

        assert!(rx.feed(header(30, 4, 0, 50), payloads[0].clone()).is_empty());
        // packets 1 and 2 lost
        assert!(rx.feed(header(33, 4, 3, 50), payloads[3].clone()).is_empty());
        assert!(rx
            .feed(
                parity_header(34, 4, parity.len_xor, parity.payload.len() as u16),
                parity.payload,
            )
            .is_empty());

        // Next group starts: previous group flushes with 2 lost.
        let out = rx.feed(header(35, 4, 0, 50), vec![9u8; 50]);
        assert_eq!(out.len(), 2);
        assert_eq!(out[0].0.sequence, 30);
        assert_eq!(out[1].0.sequence, 33);
        assert_eq!(rx.lost(), 2);
    }

    #[test]
    fn straggler_from_flushed_group_emitted_immediately() {
        let mut rx = FecReceiver::new();
        assert!(rx.feed(header(40, 2, 0, 10), vec![1; 10]).is_empty());
        // group switches before completion
        let out = rx.feed(header(42, 2, 0, 10), vec![3; 10]);
        assert_eq!(out.len(), 1); // flushed partial group
        // straggler for the flushed group (seq 41, index 1, base 40)
        let out = rx.feed(header(41, 2, 1, 10), vec![2; 10]);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0.sequence, 41);
    }

    #[test]
    fn sequence_wraparound() {
        let mut rx = FecReceiver::new();
        let payloads = vec![vec![1u8; 50], vec![2u8; 50]];
        let parity = encode_group(&payloads);

        assert!(rx.feed(header(65535, 2, 0, 50), payloads[0].clone()).is_empty());
        // packet at seq 0 (index 1) lost; parity at seq 1
        let out = rx.feed(
            parity_header(1, 2, parity.len_xor, parity.payload.len() as u16),
            parity.payload,
        );
        assert_eq!(out.len(), 2);
        assert_eq!(out[1].0.sequence, 0);
        assert_eq!(out[1].1, payloads[1]);
    }

    #[test]
    fn encoder_len_xor_matches() {
        let parity = encode_group(&[vec![1u8; 100], vec![2u8; 120], vec![3u8; 90]]);
        assert_eq!(parity.len_xor, 100u16 ^ 120 ^ 90);
        assert_eq!(parity.payload.len(), 120);
    }
}
