//! Simple XOR-based Forward Error Correction for OAAT audio packets.
//!
//! Every `group_size` data packets, a parity packet is generated by XORing
//! all data payloads in the group. If any single packet in the group is lost,
//! it can be reconstructed from the parity + the remaining packets.
//!
//! This adds ~12-25% bandwidth overhead (1/8 to 1/4) but makes Wi-Fi streaming
//! resilient to occasional packet loss without retransmission latency.

/// Encoder: accumulates packets, emits parity when group is full.
pub struct FecEncoder {
    group_size: u8,
    parity: Vec<u8>,
    count: u8,
    base_sequence: u16,
}

impl FecEncoder {
    pub fn new(group_size: u8) -> Self {
        assert!((2..=16).contains(&group_size));
        Self {
            group_size,
            parity: Vec::new(),
            count: 0,
            base_sequence: 0,
        }
    }

    /// Feed a data packet payload. Returns `Some(parity_payload)` when the group is complete.
    pub fn feed(&mut self, sequence: u16, payload: &[u8]) -> Option<Vec<u8>> {
        if self.count == 0 {
            self.base_sequence = sequence;
            self.parity.clear();
            self.parity.resize(payload.len(), 0);
        }

        // XOR into parity buffer (handle different-length packets by extending)
        if payload.len() > self.parity.len() {
            self.parity.resize(payload.len(), 0);
        }
        for (i, &b) in payload.iter().enumerate() {
            self.parity[i] ^= b;
        }

        self.count += 1;

        if self.count >= self.group_size {
            let result = self.parity.clone();
            self.count = 0;
            Some(result)
        } else {
            None
        }
    }

    pub fn group_size(&self) -> u8 {
        self.group_size
    }
}

/// Decoder: buffers packets in a group, reconstructs missing packet from parity.
pub struct FecDecoder {
    group_size: u8,
    packets: Vec<Option<Vec<u8>>>,
    parity: Option<Vec<u8>>,
    base_sequence: u16,
    active: bool,
}

impl FecDecoder {
    pub fn new(group_size: u8) -> Self {
        let gs = group_size as usize;
        Self {
            group_size,
            packets: vec![None; gs],
            parity: None,
            base_sequence: 0,
            active: false,
        }
    }

    /// Feed a data packet. `index` is position within the FEC group (0..group_size-1).
    pub fn feed_data(&mut self, index: u8, sequence: u16, payload: Vec<u8>) {
        if !self.active {
            self.base_sequence = sequence.wrapping_sub(index as u16);
            self.active = true;
        }
        if (index as usize) < self.packets.len() {
            self.packets[index as usize] = Some(payload);
        }
    }

    /// Feed the parity packet for this group.
    pub fn feed_parity(&mut self, payload: Vec<u8>) {
        self.parity = Some(payload);
    }

    /// Try to recover a missing packet. Returns `Some((index, recovered_payload))`.
    pub fn recover(&self) -> Option<(u8, Vec<u8>)> {
        let parity = self.parity.as_ref()?;

        let mut missing_idx = None;
        let mut missing_count = 0u8;

        for (i, p) in self.packets.iter().enumerate() {
            if p.is_none() {
                missing_idx = Some(i as u8);
                missing_count += 1;
            }
        }

        if missing_count != 1 {
            return None;
        }

        let idx = missing_idx.unwrap();
        let mut recovered = parity.clone();

        for (i, p) in self.packets.iter().enumerate() {
            if i == idx as usize {
                continue;
            }
            if let Some(data) = p {
                for (j, &b) in data.iter().enumerate() {
                    if j < recovered.len() {
                        recovered[j] ^= b;
                    }
                }
            }
        }

        Some((idx, recovered))
    }

    /// Reset for next group.
    pub fn reset(&mut self) {
        for p in &mut self.packets {
            *p = None;
        }
        self.parity = None;
        self.active = false;
    }

    pub fn group_size(&self) -> u8 {
        self.group_size
    }

    pub fn is_complete(&self) -> bool {
        self.packets.iter().all(|p| p.is_some())
    }

    pub fn missing_count(&self) -> u8 {
        self.packets.iter().filter(|p| p.is_none()).count() as u8
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encode_decode_no_loss() {
        let mut enc = FecEncoder::new(4);
        let payloads: Vec<Vec<u8>> = (0..4).map(|i| vec![i * 10; 960]).collect();

        for (seq, payload) in payloads.iter().enumerate() {
            let parity = enc.feed(seq as u16, payload);
            if seq < 3 {
                assert!(parity.is_none());
            } else {
                assert!(parity.is_some());
            }
        }
    }

    #[test]
    fn recover_single_loss() {
        let mut enc = FecEncoder::new(4);
        let payloads: Vec<Vec<u8>> = vec![
            vec![0xAA; 100],
            vec![0xBB; 100],
            vec![0xCC; 100],
            vec![0xDD; 100],
        ];

        let mut parity = Vec::new();
        for (seq, payload) in payloads.iter().enumerate() {
            if let Some(p) = enc.feed(seq as u16, payload) {
                parity = p;
            }
        }

        // Simulate loss of packet index 2
        let mut dec = FecDecoder::new(4);
        dec.feed_data(0, 0, payloads[0].clone());
        dec.feed_data(1, 1, payloads[1].clone());
        // packet 2 lost
        dec.feed_data(3, 3, payloads[3].clone());
        dec.feed_parity(parity);

        assert_eq!(dec.missing_count(), 1);
        let (idx, recovered) = dec.recover().unwrap();
        assert_eq!(idx, 2);
        assert_eq!(recovered, payloads[2]);
    }

    #[test]
    fn two_losses_not_recoverable() {
        let mut enc = FecEncoder::new(4);
        let payloads: Vec<Vec<u8>> = (0..4).map(|i| vec![i; 50]).collect();

        let mut parity = Vec::new();
        for (seq, payload) in payloads.iter().enumerate() {
            if let Some(p) = enc.feed(seq as u16, payload) {
                parity = p;
            }
        }

        let mut dec = FecDecoder::new(4);
        dec.feed_data(0, 0, payloads[0].clone());
        // packets 1 and 2 lost
        dec.feed_data(3, 3, payloads[3].clone());
        dec.feed_parity(parity);

        assert_eq!(dec.missing_count(), 2);
        assert!(dec.recover().is_none());
    }
}
